
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class Register extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    Connection cn = koneksi.koneksi.BukaKoneksi();
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        setLocationRelativeTo(null);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        g1 = new javax.swing.JLabel();
        g2 = new javax.swing.JLabel();
        g3 = new javax.swing.JLabel();
        Jnama = new javax.swing.JTextField();
        Jusername = new javax.swing.JTextField();
        Jpassword = new javax.swing.JPasswordField();
        BRegist = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        g4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 255, 255));
        t1.setText("Username");
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        t2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 255, 255));
        t2.setText("Password");
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        t3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        t3.setForeground(new java.awt.Color(255, 255, 255));
        t3.setText("Nama");
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        g1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        g1.setForeground(new java.awt.Color(255, 255, 255));
        g1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 167, -1));

        g2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        g2.setForeground(new java.awt.Color(255, 255, 255));
        g2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 167, -1));

        g3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        g3.setForeground(new java.awt.Color(255, 255, 255));
        g3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(g3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 167, -1));

        Jnama.setBackground(new java.awt.Color(51, 0, 153));
        Jnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jnama.setForeground(new java.awt.Color(255, 255, 255));
        Jnama.setBorder(null);
        jPanel1.add(Jnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 167, -1));

        Jusername.setBackground(new java.awt.Color(51, 0, 153));
        Jusername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jusername.setForeground(new java.awt.Color(255, 255, 255));
        Jusername.setBorder(null);
        jPanel1.add(Jusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 167, -1));

        Jpassword.setBackground(new java.awt.Color(51, 0, 153));
        Jpassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Jpassword.setForeground(new java.awt.Color(255, 255, 255));
        Jpassword.setBorder(null);
        jPanel1.add(Jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 167, -1));

        BRegist.setBackground(new java.awt.Color(51, 0, 153));
        BRegist.setText("Daftar");
        BRegist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegistActionPerformed(evt);
            }
        });
        jPanel1.add(BRegist, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 167, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Do You Have Account ?");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 320));

        jPanel2.setBackground(new java.awt.Color(13, 36, 81));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrasi");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 140, 60));

        g4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        g4.setForeground(new java.awt.Color(255, 255, 255));
        g4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.add(g4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 76, 160, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 0, 210, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BRegistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegistActionPerformed
        try{
            st = cn.createStatement();
            if(Jpassword.getPassword().equals("")||Jnama.getText().equals("")||Jusername.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong","Pesan",JOptionPane.ERROR_MESSAGE);
            }
            if(BRegist.getText() == "Daftar"){
                String cek  = "SELECT * FROM login WHERE username ='"+Jusername.getText()+"'";
                rs = st.executeQuery(cek);
                if (rs.next()){
                    JOptionPane.showMessageDialog(null, "Nama Sudah Terpakai");
                }else{
//                    String sql ="INSERT INTO login VALUES ('" + txtusername.getText() + "','" + String.valueOf(txtpass.getPassword()) + "' )";
                    String sql = "INSERT INTO login(nama,username,password) VALUES ('"+Jnama.getText()+"','"
                        +Jusername.getText()+"','"+String.valueOf(Jpassword.getPassword())+"')";
                    st.execute(sql);
                    JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan");
                }
            }
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this,"Akun Sudah Ada","Pesan",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BRegistActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Login lg = new Login();
        lg.setVisible(true);
        lg.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BRegist;
    private javax.swing.JTextField Jnama;
    private javax.swing.JPasswordField Jpassword;
    private javax.swing.JTextField Jusername;
    private javax.swing.JLabel g1;
    private javax.swing.JLabel g2;
    private javax.swing.JLabel g3;
    private javax.swing.JLabel g4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    // End of variables declaration//GEN-END:variables
}
